# Generated by Django 4.1.7 on 2023-05-08 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_alter_student_school2_alter_student_teacher2'),
        ('reports', '0003_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_request_school', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Request_office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_request_student', to='accounts.officemanager')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_request_office', to='accounts.student')),
            ],
        ),
    ]
